@host = :8081
@tokens = :8081
@usery = :8080
@basic = BasiC YWRtaW46YWRtaW4=
@jwt_refresh = BeareR eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwczovL2F1dGguaGFja25pZ2h0cy5jbHViIiwiZXhwIjoxNTUxNjYwMjE5LCJpYXQiOjE1NTEwNTU0MTksImlzcyI6Imh0dHBzOi8vYXV0aC5oYWNrbmlnaHRzLmNsdWIiLCJyZXYiOm51bGwsInN1YiI6ImFub255bW91cyIsInR5cCI6InJlZnJlc2gifQ.DEHfTgIQa73Eeb6ycJzlic7uG9OQO6RiBhjE-XAw-izDJD1OFfwmFhksKr-j3ojWMltXWBtK3MKzbanjVFj9wPqyyeKBDztwMEiaLXIYPXULqK9Q3MAdMoWQUbob0hKMmozHKHN6Lq81yjq8u3_ifd0d0uJzOHIi1EnDfUcLMg6VAQkOwfEnjwLeghw-DdIxLwzdp_NB71uEQ7OcqB-C7jPV_xRNiuVhZpI8ji6BiKjOoRRbyYNeHdLuAnZFlU5u4aoZKE5GEjYlZizczMoevNhq25X1dyJBbT6kz1H6Cs2m8ApepUKQV8bnEJPFiegcuFMBp7VNWmFhLfdxgPjS5e5FZzwanYWBTuDJ3XqHAzhqTvsK-2pyzDlXrAuka6KQttnxB2Z28i3fWvU1IOWpEHffpjNF_pwTMa6HV4_qpoD4RgKP3bWKSHDvd-_PM5kNMiX1mq4UybS2Rbim-pyvsGICmI8zBL4q1v4IQpbFG2QC1ZFRdBEAK_y-p5cRTgyl8TmgoVQWEhDryVCysp9SaUmrh_zVaJYyV6N9q_Px_F5wIRDSmW5k2mSWrTPZ5akgIx-zPVuPXl7U1FxcOn0G41fWA84RluwOz3foQI52UIduhZ6pvdvbj9GNUUoaU3CNIwly2sUBmZGa3J-tYhV2LoDGUp0866O9WDbfypqkDO0
@jwt_access = BeareR eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwczovL2FwaS5oYWNrbmlnaHRzLmNsdWIiLCJleHAiOjE1NTEwNTkwMTksImlhdCI6MTU1MTA1NTQxOSwiaXNzIjoiaHR0cHM6Ly9hdXRoLmhhY2tuaWdodHMuY2x1YiIsInN1YiI6ImFub255bW91cyIsInR5cCI6ImFjY2VzcyJ9.bt5sFpZ_Zd9JXyU9-1YMKhcDGsNxAQaTz3_Dg-JIRpW_ULNjUpfMd19nrzl7uz9421-HeZKNYmpE6ylcNwFu2OTooVDxG3oH9gfveK_RK1B0uKmN2pN5eWYMz9vabCRMg9qvR8xXwW2V1bh9fkMyHjYawVKquhaW8HVEQaosrZSF9yXGxLzsSguTlrD7Ww0w5xuMJvHld4BlXAerVPYgPT2zcU1Msni-oxrxtfHKCgdvLHnH7eAVrh1Io4sonmb9vNPONffTW-BkQoqPddXz5SafhZ7et1x3v0qTXeK6G_xsvQ-0jrkK94qkfy6MVkeiGu_y_L52x4LXz_x3LhOGlPLCH6zWy3Ag1PsjGFlHneqxxTWsDB3HSgebT8ZTmBTI9-XGtx055zszo_Ebd1DjmBJhVHONi7t-LYnjXfZqiudQbQFw_-VEqe06tzTxC_6ZFz2T9DXCv75ODCiq5j_Wo3UlwrET2SRs6931hIoRK3sHd5kj5uwsJVq6HaVvC_Af7daH40X6EzB3VkFXAiMTIqcaTRBeiAW4CWEM6SC-Xhp8P4y7nldaxfnDPNYI-N7_SKPP3GOA6OW_nGAEIoKBMkQg3bOj0t119hZPazCU_x6iEMy15eOirgauRoqnVnU2wDUe6cwWTxBI5wKV7xYdWtQ_qPbzGm-L_iBxz-Kiryc

### DEBUG
GET http://{{tokens}}/debug/vars

### Get protected content
GET http://{{tokens}}/restricted
Authorization: {{jwt_access}}

### Hello
GET http://{{tokens}}

### Authenticate Basic
GET http://{{usery}}/api/authenticate
Authorization: {{basic}}

### Authenticate Bearer <Refresh>
GET http://{{usery}}/api/authenticate
Authorization: {{jwt_refresh}}

### Authenticate Bearer <Access>
GET http://{{usery}}/api/authenticate
Authorization: {{jwt_access}}

### GET Users
GET http://{{usery}}/api/users/:uid/claims
Authorization: {{jwt_access}}


### Generate tokens with Basic
GET http://{{tokens}}/tokens/:appId
Authorization: {{basic}}

### Generate tokens with Refresh
GET http://{{tokens}}/tokens
Authorization: {{jwt_refresh}}

### Generate tokens with Access
GET http://{{tokens}}/tokens
Authorization: {{jwt_access}}


### Refresh tokens with Refresh
GET http://{{tokens}}/refresh
Authorization: {{jwt_refresh}}


### Refresh tokens with Access
GET http://{{tokens}}/refresh
Authorization: {{jwt_access}}




############################################
### .status - standard health and monitoring
############################################

### about
GET http://{{host}}/.status

### liveness check
HEAD http://{{host}}/.status/alive

### ready check
HEAD http://{{host}}/.status/ready

### health check
GET http://{{host}}/.status/health

### metrics check
GET http://{{host}}/.status/metrics

### verify logging
GET http://{{host}}/.status/logged

### Verify security
GET http://{{host}}/.status/secured