@host = :8080
@basic = Basic YWRtaW46YWRtaW4=
@jwt_refresh = Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwczovL2FwaS5hdXRoaWRhdGUuY29tIiwiZXhwIjoxNTUwNDU5NDUxLCJpYXQiOjE1NDk4NTQ2NTEsImlzcyI6Imh0dHBzOi8vYXV0aC5hdXRoaWRhdGUuY29tIiwianRpIjoidXVpZCIsInN1YiI6ImFub255bW91cyJ9.kh7fm381TgjjQOvYrS6NZVD_03-Ifuam3iM15W_6De0hbCswFZysF1SsPrupjfkoP-dWU1wAuwL9c8K8s-AUeKZuTRjLCpfqnZ9TJaTAnz4z3Ig5iF8Xk1sOpPp8bvo3e9DvNeQFK99SuZegMK_8rdo77UO6iwvhWe5EXB15Wa3HGnTd0N0IZAe3FOF9cZyAyBvjY52m9XqxApZppVkpjdwejs_e4em_foHhwvDOX6A1TfN7U4ZUzmm8HVDuac_e4bUMfXJTV4dtk3fn5DI5lBx-eAxkV6razBGo_Xuz2I6Zh9mpqvwADR-pv7ayqtYKwu3gW8O9JnzMR6oeNL1OmKl_5RiMmVXWfrHyiFnYdqLHpELvNb2nvRLavLddaGlJga9qCG1Zd4YvuIh1SQqOXsDbW9KL9ocNqxe2YKTqBx06WneznYms-rhCp0padqKl4KIHR6y2NPHyvNwsRgj7_46IzG4WUP4hJLEPArN2dH79WUmuw9bsxgVYzPvrPyagDFJtbvTPx4WMuetCQf5o25e5Y3czFSlxRfL6ct7CPbUoDe6ixULJrIuYB1E1WlOLR0D-f3t1MD5JYFmS3YnGR8jm11JM2rqUmiDqpztT8VZEUkDdZy26CnnuKcgCFpJss8HIOVZG4WfC1xzr_wBn_zXs9_RWLEL9KJ9gEGkP7xE
@jwt_access = Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwczovL2FwaS5hdXRoaWRhdGUuY29tIiwiZXhwIjoxNTQ5ODU0NzExLCJpYXQiOjE1NDk4NTQ2NTEsImlzcyI6Imh0dHBzOi8vYXV0aC5hdXRoaWRhdGUuY29tIiwic3ViIjoiYW5vbnltb3VzIn0.QK2y_NTuOh7qlE2Wh20whlCNLfQX_3G4WjSXctChwdJ3kyY2UoFJjyskvGdxMA5ynmD36cNcygpyZSWSC2xRbqMy4h4vrKmNpW-Vw0tJ_pLvCvfTTPLNvlgGK_7Vu3UFMjjVFsyXisF-D880qs1dgrrxzLD0X7ISrKfqsCP5oe7rPpYW4QgLfzY3gOqNCNtUQNl8K4hldGFU_Q3RyM1WpoTBPo_F72o0jpw1BVUGBBXIlTOyu_yfG122rBRrN6gmJjAhr_OVuwgdRy_UeYrqTESL1Ld0gCG5izxMg2Dks2RjMUWkzxhUn89pvBdAQCR-5pBvgClsXKdHz7beK95Fg0g3Gx5HJclg3m_FqiRpOPnBvl8NOz_FUUAP2cf5x6pETpvpfdJtrKAORigapVhmSIZ2JfqQH5gisPGE4XfGORTU9_E8nLg49o_848EoFvOfLsyVpyLtHQWRES4E2xxOU5TI6sAbT_sw_G18M3-rfEHfJQ8Gwg74RFUa3Ginat0PPwbBuH4KC2LjtoAaI18NC1BcTc8uJB8j9VZBvgAlYdx7vICIV14xWMD0xlUapQAhL2uzzp7OjG-5iHbfuQPQptW17vAC5JYWjBlwYC59QmI64bjid_UtXxcu5RP6erYTzXXcqsNgJuKAkfdMkLod2X0Okbs2CTB2m22tcJJed2I

### Hello
GET http://{{host}}

### Generate tokens with credentials
GET http://{{host}}/tokens
Authorization: {{basic}}

### Generate tokens with Refresh
GET http://{{host}}/tokens/refresh
Authorization: {{jwt_refresh}}

### Blacklist current refresh token
GET http://{{host}}/tokens/revoke
Authorization: {{jwt_refresh}} 

### Blacklist all refresh tokens for current user
GET http://{{host}}/tokens/revoke-all
Authorization: {{jwt_refresh}} 

### Get protected content
GET http://{{host}}/restricted
Authorization: {{jwt_access}}




############################################
### .status - standard health and monitoring
############################################

### about
GET http://{{host}}/.status

### liveness check
HEAD http://{{host}}/.status/alive

### ready check
HEAD http://{{host}}/.status/ready

### health check
GET http://{{host}}/.status/health

### metrics check
GET http://{{host}}/.status/metrics

### verify logging
GET http://{{host}}/.status/logged

### Verify security
GET http://{{host}}/.status/secured