@host = :8081
@tokens = :8081
@usery = :8080
@basic = BasiC YWRtaW46YWRtaW4=
@jwt_refresh = BeareR eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwczovL2FwaS5oYWNrbmlnaHRzLmNsdWIiLCJleHAiOjE1NTE1NTAyMjksImlhdCI6MTU1MDk0NTQyOSwiaXNzIjoiaHR0cHM6Ly9hdXRoLmhhY2tuaWdodHMuY2x1YiIsInJldiI6bnVsbCwic3ViIjoiYWJjMTIzIiwidHlwIjoicmVmcmVzaCJ9.Pn4pl9MIwFO18rOQ1EA1ytBy_cNxDnaKgZkw4P4dc34n55XiTsNLgoAnOKMfPzA7b5jrhaEuYUskiCQ_9Lh3H3BovQEmE5aHOfYoAQNb3OGIvoEpzIkD8nOmmomRcviQwAaczptlKg4bxTGivh6ucVmJVKK3SkSABVIoYRyB-N7i9mtZb0zL_UtYlnictvjED1skA2g948UnADHZ-Nyle04L5xt8K8rifFZoslLT2THXahBG0aAcQJj3GEAzYH6iW06CTnx05mDoCoBoiS4F_01cY_zUTjasFv29Tby-5zhmaHQ3g_AjqyIjV-wOdr-A3fO7RMaNMg_Fu8Bbn_2iOmlgTwuCfdxfxIQ_FdMrDCVWQZJw8ABYLFAI27YwNjuS-3LGymohxD1lspRqXgEP8wDy85PDgZUKDFXSyLAAi6N14sNaEpIiNJBvkOUCPD5EviS9wI9HXTjiuo3lyRjyWzYsVGGPUt0sWM5-_0SnpG-_4ED4E4J-xmJqenngFX9BC5-htTdeMaJZ9p3ujkerZCN5C_BKVryBnCR0Mg--crh4tkenwUTsLzvFTlkzYjN-4y0stqIzSkWUw8DZJb7phyjdFK54CBibrs37rrcIZ3YD1vxkxsRbWs9YO-4s1jB4Ym7tm9XoWIBxksM1Y9KnTNDljYz0CeDWw4ft4LkMN2U
@jwt_access = BeareR eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwczovL2FwaS5oYWNrbmlnaHRzLmNsdWIiLCJleHAiOjE1NTA5NDU0ODksImlhdCI6MTU1MDk0NTQyOSwiaXNzIjoiaHR0cHM6Ly9hdXRoLmhhY2tuaWdodHMuY2x1YiIsInN1YiI6ImFiYzEyMyIsInR5cCI6ImFjY2VzcyJ9.SJQYLkTth0mxmQ9LJ8kDqW5E2BzJcWJg7hkilo3L6y02XMsp-W4WvGsfeR948NvZWIdk3LFa7hx0xtmQrM9lrHZwK_oMZgkngAgqTwUZstqcySulql8gyj76wjybfGtj5H4QCPh1Km-HlfKDKtTCnnTUihSLMHYKqYA1wEYykMc9yUaKdlh10rhCOg5nUYalhIh15kmXCU5KMD0MuGk3-fV25dLgkX_PerSjW5nNw4LaQ85kWrGTgOdN4EZi4gzkb90fn5B2Nlpd3210cndsNr0NtGu_0GdCvtUmPVvuRwE4Hdtq-jscWthPxlMOT5SIe82l_bz5eqCJOZaBGj3C0OAg4Pic3KrVFxEx0LvfYXPv858M0IXFfuSA845iTzrB4YURyRgraokgEl4ZYZ0qwNe51cYFa-2MHZKGOXj5_pQGwdTRipb8SYFw2yW3xtxkGqdHXXLi0tRk88KKD-LrfsTGsaGnVNRW7HSUJ13VhYUUAwLDbNvsMUqPwEvHFU2P2duD0ZfKxlobHvzR3Hq9-IHdwNUfablfVqB4c_DDARH0eWJJ9UzW5wzBDj_7botAnn757aE8ASllnSukHLwHNKi1Og47MD_I4RNyhJh9ezxjlEAiRIUDAbrp1nEgCL1SEph00_hj2hTPru_JxJPfS1FjegEoxLJnmR7ySkIglTs

### DEBUG
GET http://{{tokens}}/debug/vars

### Get protected content
GET http://{{tokens}}/restricted
Authorization: {{jwt_access}}

### Hello
GET http://{{tokens}}

### Authenticate Basic
GET http://{{usery}}/api/authenticate
Authorization: {{basic}}

### Authenticate Bearer <Refresh>
GET http://{{usery}}/api/authenticate
Authorization: {{jwt_refresh}}

### Authenticate Bearer <Access>
GET http://{{usery}}/api/authenticate
Authorization: {{jwt_access}}

### GET Users
GET http://{{usery}}/api/users/:uid/claims
Authorization: {{jwt_access}}


### Generate tokens with credentials
GET http://{{tokens}}/tokens
Authorization: {{basic}}

### Generate tokens with Refresh
GET http://{{tokens}}/tokens
Authorization: {{jwt_refresh}}




############################################
### .status - standard health and monitoring
############################################

### about
GET http://{{host}}/.status

### liveness check
HEAD http://{{host}}/.status/alive

### ready check
HEAD http://{{host}}/.status/ready

### health check
GET http://{{host}}/.status/health

### metrics check
GET http://{{host}}/.status/metrics

### verify logging
GET http://{{host}}/.status/logged

### Verify security
GET http://{{host}}/.status/secured